/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'n-tange' at '15/12/12 15:37' with Gradle 2.8
 *
 * @author n-tange, @date 15/12/12 15:37
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
